# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(306, 340)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_num_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_num_1.setGeometry(QtCore.QRect(40, 30, 71, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_num_1.setFont(font)
        self.label_num_1.setObjectName("label_num_1")
        self.label_num_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_num_2.setGeometry(QtCore.QRect(40, 60, 71, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.label_num_2.setFont(font)
        self.label_num_2.setObjectName("label_num_2")
        self.lineEditNum1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNum1.setGeometry(QtCore.QRect(110, 45, 120, 20))
        self.lineEditNum1.setObjectName("lineEditNum1")
        self.lineEditNum2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNum2.setGeometry(QtCore.QRect(110, 75, 120, 20))
        self.lineEditNum2.setObjectName("lineEditNum2")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(110, 110, 120, 25))
        self.addButton.setObjectName("addButton")
        self.buttonSubstract = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSubstract.setGeometry(QtCore.QRect(110, 150, 120, 25))
        self.buttonSubstract.setObjectName("buttonSubstract")
        self.buttonMultiply = QtWidgets.QPushButton(self.centralwidget)
        self.buttonMultiply.setGeometry(QtCore.QRect(110, 190, 120, 25))
        self.buttonMultiply.setObjectName("buttonMultiply")
        self.buttonDivide = QtWidgets.QPushButton(self.centralwidget)
        self.buttonDivide.setGeometry(QtCore.QRect(110, 230, 120, 25))
        self.buttonDivide.setObjectName("buttonDivide")
        self.labelResult = QtWidgets.QLabel(self.centralwidget)
        self.labelResult.setGeometry(QtCore.QRect(40, 250, 60, 50))
        self.labelResult.setObjectName("labelResult")
        self.labelResult2 = QtWidgets.QLabel(self.centralwidget)
        self.labelResult2.setGeometry(QtCore.QRect(40, 270, 47, 13))
        self.labelResult2.setText("")
        self.labelResult2.setObjectName("labelResult2")
        self.resultLabel2 = QtWidgets.QLabel(self.centralwidget)
        self.resultLabel2.setGeometry(QtCore.QRect(80, 270, 47, 13))
        self.resultLabel2.setText("")
        self.resultLabel2.setObjectName("resultLabel2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 306, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hesap Makinesi"))
        self.label_num_1.setText(_translate("MainWindow", "1st Number:"))
        self.label_num_2.setText(_translate("MainWindow", "2nd Number:"))
        self.addButton.setText(_translate("MainWindow", "Add"))
        self.buttonSubstract.setText(_translate("MainWindow", "Substract"))
        self.buttonMultiply.setText(_translate("MainWindow", "Multiply"))
        self.buttonDivide.setText(_translate("MainWindow", "Divide"))
        self.labelResult.setText(_translate("MainWindow", "Result :"))
