# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(398, 348)
        MainWindow.setStyleSheet("background-color: rgb(255, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelNum1 = QtWidgets.QLabel(self.centralwidget)
        self.labelNum1.setGeometry(QtCore.QRect(30, 40, 290, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(10)
        self.labelNum1.setFont(font)
        self.labelNum1.setObjectName("labelNum1")
        self.lineEditGuess = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditGuess.setGeometry(QtCore.QRect(250, 40, 100, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        self.lineEditGuess.setFont(font)
        self.lineEditGuess.setObjectName("lineEditGuess")
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setGeometry(QtCore.QRect(250, 80, 100, 30))
        self.sendButton.setObjectName("sendButton")
        self.labelNum2 = QtWidgets.QLabel(self.centralwidget)
        self.labelNum2.setGeometry(QtCore.QRect(30, 150, 200, 20))
        self.labelNum2.setText("")
        self.labelNum2.setObjectName("labelNum2")
        self.labelNum3 = QtWidgets.QLabel(self.centralwidget)
        self.labelNum3.setGeometry(QtCore.QRect(30, 200, 200, 20))
        self.labelNum3.setText("")
        self.labelNum3.setObjectName("labelNum3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 398, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Guess The Number"))
        self.labelNum1.setText(_translate("MainWindow", "Type a guess between 1 and 100 :"))
        self.sendButton.setText(_translate("MainWindow", "Send"))
